stub-sp:
  extends:
    file: common.yaml
    service: eidas
  image: eidas/tomcat:8-oracle-java8
  ports:
    - "${STUB_SP_HTTP_PORT}:8080"
  volumes:
    - ../EIDAS-SP/target/SP.war:/usr/local/tomcat/webapps/ROOT.war
    - ../EIDAS-SP/target/SP:/usr/local/tomcat/webapps/ROOT
    - ../EIDAS-Config:/usr/local/share/eidas
  environment:
    - "EIDAS_CONFIG_REPOSITORY=/usr/local/share/eidas/"
    - "STUB_SP_KEYSTORE=/usr/local/tomcat/webapps/ROOT/WEB-INF/stubSpKeystore.jks"
    - "STUB_SP_KEYSTORE_PASSWORD=Password"
    - "STUB_SP_ENCRYPTION_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Stub SP Encryption 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
    - "STUB_SP_ENCRYPTION_CERTIFICATE_SERIAL_NUMBER=41573ab34ef7100cb77e4c5aca551826cf86a1e9"
    - "STUB_SP_SIGNING_CERTIFICATE_DISTINGUSHED_NAME=CN=Test Stub SP Metadata Signing 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
    - "STUB_SP_SIGNING_CERTIFICATE_SERIAL_NUMBER=123f7141d99aa3b6ad31211dabb9ca7abdc08b5d"

connector-node:
  extends:
    file: common.yaml
    service: eidas
  image: eidas/tomcat:8-oracle-java8
  ports:
    - "${CONNECTOR_NODE_HTTP_PORT}:8080"
  volumes:
    - ../EIDAS-Node/target/EidasNode.war:/usr/local/tomcat/webapps/ROOT.war
    - ../EIDAS-Node/target/EidasNode:/usr/local/tomcat/webapps/ROOT
    - ../EIDAS-Config:/usr/local/share/eidas
  environment:
    - "EIDAS_CONFIG_REPOSITORY=/usr/local/share/eidas/"
    - "NODE_KEYSTORE=/usr/local/tomcat/webapps/ROOT/WEB-INF/connectorNodeKeystore.jks"
    - "NODE_KEYSTORE_PASSWORD=Password"
    - "NODE_ENCRYPTION_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Connector Encryption 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
    - "NODE_SIGNING_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Connector Metadata Signing 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
    - "NODE_ENCRYPTION_CERTIFICATE_SERIAL_NUMBER=1dcfdeedc8983a5f13f2338e0814b6e47090b3d7"
    - "NODE_SIGNING_CERTIFICATE_SERIAL_NUMBER=56520de46a76cb6ad7b9c238dd253d88904da9d8"
    - "PROXY_METADATA_URL=http://proxy-node-1/ServiceMetadata"
    - "NODE_METADATA_SSO_LOCATION=http://localhost:${CONNECTOR_NODE_HTTP_PORT}/ColleagueRequest"

proxy-node-1:
  extends:
    file: common.yaml
    service: eidas
  image: eidas/tomcat:8-oracle-java8
  ports:
    - "${COUNTRY_1_PROXY_NODE_HTTP_PORT}:8080"
  volumes:
    - ../EIDAS-Node/target/EidasNode.war:/usr/local/tomcat/webapps/ROOT.war
    - ../EIDAS-Node/target/EidasNode:/usr/local/tomcat/webapps/ROOT
    - ../EIDAS-Config:/usr/local/share/eidas
  environment:
    - "EIDAS_CONFIG_REPOSITORY=/usr/local/share/eidas/"
    - "NODE_KEYSTORE=/usr/local/tomcat/webapps/ROOT/WEB-INF/proxyNodeKeystore.jks"
    - "NODE_KEYSTORE_PASSWORD=Password"
    - "NODE_ENCRYPTION_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Proxy Encryption 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
    - "NODE_SIGNING_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Proxy Metadata Signing 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
    - "NODE_ENCRYPTION_CERTIFICATE_SERIAL_NUMBER=6641716bee633fb618dbd85b7d41e63b62046c2d"
    - "NODE_SIGNING_CERTIFICATE_SERIAL_NUMBER=203b6cb0714922c675e08606187e75c4c4457a1c"
    - "PROXY_METADATA_URL=http://localhost:${COUNTRY_1_PROXY_NODE_HTTP_PORT}/ServiceMetadata"
    - "NODE_METADATA_SSO_LOCATION=http://localhost:${CONNECTOR_NODE_HTTP_PORT}/ColleagueRequest"
    - "IDP_URL=http://stub-idp-1"
    - "IDP_SSO_URL=http://stub-idp-1"
    - "SERVICE_METADATA_URL=http://localhost:${COUNTRY_1_PROXY_NODE_HTTP_PORT}/ServiceMetadata"

proxy-node-2:
  extends:
    file: common.yaml
    service: eidas
  image: eidas/tomcat:8-oracle-java8
  ports:
    - "${COUNTRY_2_PROXY_NODE_HTTP_PORT}:8080"
  volumes:
    - ../EIDAS-Node/target/EidasNode.war:/usr/local/tomcat/webapps/ROOT.war
    - ../EIDAS-Node/target/EidasNode:/usr/local/tomcat/webapps/ROOT
    - ../EIDAS-Config:/usr/local/share/eidas
  environment:
    - "EIDAS_CONFIG_REPOSITORY=/usr/local/share/eidas/"
    - "NODE_KEYSTORE=/usr/local/tomcat/webapps/ROOT/WEB-INF/proxyNodeKeystore.jks"
    - "NODE_KEYSTORE_PASSWORD=Password"
    - "NODE_ENCRYPTION_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Proxy Encryption 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
    - "NODE_SIGNING_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Proxy Metadata Signing 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
    - "NODE_ENCRYPTION_CERTIFICATE_SERIAL_NUMBER=6641716bee633fb618dbd85b7d41e63b62046c2d"
    - "NODE_SIGNING_CERTIFICATE_SERIAL_NUMBER=203b6cb0714922c675e08606187e75c4c4457a1c"
    - "PROXY_METADATA_URL=http://localhost:${COUNTRY_2_PROXY_NODE_HTTP_PORT}/ServiceMetadata"
    - "NODE_METADATA_SSO_LOCATION=http://localhost:${CONNECTOR_NODE_HTTP_PORT}/ColleagueRequest"
    - "IDP_URL=http://stub-idp-2"
    - "IDP_SSO_URL=http://stub-idp-2"
    - "SERVICE_METADATA_URL=http://localhost:${COUNTRY_2_PROXY_NODE_HTTP_PORT}/ServiceMetadata"

stub-idp-1:
  extends:
    file: common.yaml
    service: eidas
  image: eidas/tomcat:8-oracle-java8
  ports:
    - "${COUNTRY_1_STUB_IDP_HTTP_PORT}:8080"
  volumes:
    - ../EIDAS-IdP-1.0/target/IdP.war:/usr/local/tomcat/webapps/ROOT.war
    - ../EIDAS-IdP-1.0/target/IdP:/usr/local/tomcat/webapps/ROOT
    - ../EIDAS-Config:/usr/local/share/eidas
  environment:
    - "EIDAS_CONFIG_REPOSITORY=/usr/local/share/eidas/"
    - "STUB_IDP_KEYSTORE=/usr/local/tomcat/webapps/ROOT/WEB-INF/stubIdpKeystore.jks"
    - "STUB_IDP_KEYSTORE_PASSWORD=Password"
    - "STUB_IDP_ENCRYPTION_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Stub IdP Encryption 20161031, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
    - "STUB_IDP_ENCRYPTION_CERTIFICATE_SERIAL_NUMBER=723c0f7f4b45dea5296e53f565535174d0df5218"
    - "STUB_IDP_SIGNING_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Stub IdP Metadata Signing 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
    - "STUB_IDP_SIGNING_CERTIFICATE_SERIAL_NUMBER=5ae2153c3f9a99824df394abd65f9e1e8ca53365"
    - "PROXY_METADATA_URL=http://proxy-node-1/ServiceMetadata"
    - "PROXY_URL=http://proxy-node-1/"
    - "NODE_METADATA_SSO_LOCATION=http://localhost:${COUNTRY_1_PROXY_NODE_HTTP_PORT}/ColleagueRequest"
    - "IDP_URL=http://localhost:${COUNTRY_1_STUB_IDP_HTTP_PORT}"
    - "IDP_SSO_URL=http://localhost:${COUNTRY_1_STUB_IDP_HTTP_PORT}"
    - "IDP_COUNTRY_CODE=NL"
    - "SP_URL="
    - "COUNTRY_1_CODE="
    - "COUNTRY_1_NAME="
    - "COUNTRY_1_PROXY_URL="
    - "COUNTRY_2_CODE="
    - "COUNTRY_2_NAME="
    - "COUNTRY_2_PROXY_URL="

stub-idp-2:
  extends:
    file: common.yaml
    service: eidas
  image: eidas/tomcat:8-oracle-java8
  ports:
    - "${COUNTRY_2_STUB_IDP_HTTP_PORT}:8080"
  volumes:
    - ../EIDAS-IdP-1.0/target/IdP.war:/usr/local/tomcat/webapps/ROOT.war
    - ../EIDAS-IdP-1.0/target/IdP:/usr/local/tomcat/webapps/ROOT
    - ../EIDAS-Config:/usr/local/share/eidas
  environment:
    - "EIDAS_CONFIG_REPOSITORY=/usr/local/share/eidas/"
    - "STUB_IDP_KEYSTORE=/usr/local/tomcat/webapps/ROOT/WEB-INF/stubIdpKeystore.jks"
    - "STUB_IDP_KEYSTORE_PASSWORD=Password"
    - "STUB_IDP_ENCRYPTION_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Stub IdP Encryption 20161031, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
    - "STUB_IDP_ENCRYPTION_CERTIFICATE_SERIAL_NUMBER=723c0f7f4b45dea5296e53f565535174d0df5218"
    - "STUB_IDP_SIGNING_CERTIFICATE_DISTINGUISHED_NAME=CN=Test Stub IdP Metadata Signing 20161026, OU=Government Digital Service, O=Cabinet Office, L=London, ST=Greater London, C=UK"
    - "STUB_IDP_SIGNING_CERTIFICATE_SERIAL_NUMBER=5ae2153c3f9a99824df394abd65f9e1e8ca53365"
    - "PROXY_METADATA_URL=http://proxy-node-2/ServiceMetadata"
    - "PROXY_URL=http://proxy-node-2/"
    - "NODE_METADATA_SSO_LOCATION=http://localhost:${COUNTRY_2_PROXY_NODE_HTTP_PORT}/ColleagueRequest"
    - "IDP_URL=http://localhost:${COUNTRY_2_STUB_IDP_HTTP_PORT}"
    - "IDP_SSO_URL=http://localhost:${COUNTRY_2_STUB_IDP_HTTP_PORT}"
    - "IDP_COUNTRY_CODE=ES"
    - "SP_URL="
    - "SERVICE_METADATA_URL="
    - "CONNECTOR_URL="
    - "COUNTRY_1_CODE="
    - "COUNTRY_1_NAME="
    - "COUNTRY_1_PROXY_URL="
    - "COUNTRY_2_CODE="
    - "COUNTRY_2_NAME="
    - "COUNTRY_2_PROXY_URL="
